// Module included in the following assemblies:
//
// * virt/virtual_machines/creating_vm/virt-creating-vms-from-templates.adoc

:_mod-docs-content-type: PROCEDURE
[id="virt-creating-template_{context}"]
= Creating a custom virtual machine template in the web console

[role="_abstract"]
You can create a custom virtual machine (VM) template by editing a YAML example in the {product-title} web console.

.Procedure

. In the {product-title} web console, click *Virtualization* -> *Templates* in the side menu.
. Optional: Use the *Project* drop-down menu to change the project associated with the new template. All templates are saved to the `openshift` project by default.
. Click *Create Template*.
. Specify the template parameters by editing the YAML file.
. Click *Create*.
+
The template is displayed on the *Templates* page.
. Optional: Click *Download* to download and save the YAML file.
. Optional: Enable dedicated resources for the template. For information about configuring dedicated resources, see the procedure about enabling dedicated resources for a VM template.
