// Module included in the following assemblies:
//
// * virt/updating/upgrading-virt.adoc

:_mod-docs-content-type: CONCEPT
[id="virt-about-control-plane-only-updates_{context}"]
= Control Plane Only updates

[role="_abstract"]
Every even-numbered minor version of {product-title} is an Extended Update Support (EUS) version. However, Kubernetes design mandates serial minor version updates, so you cannot directly update from one EUS version to the next.

An EUS-to-EUS update starts with updating {VirtProductName} to the latest z-stream of the next odd-numbered minor version. Next, update {product-title} to the target EUS version. When the {product-title} update succeeds, the corresponding update for {VirtProductName} becomes available. You can now update {VirtProductName} to the target EUS version.

[NOTE]
====
You can directly update {VirtProductName} to the latest z-stream release of your current minor version without applying each intermediate z-stream update.
====

For more information about EUS versions, see the link:https://access.redhat.com/support/policy/updates/openshift[{product-title} Life Cycle Policy].

[id="prerequisites_{context}"]
== Prerequisites

Before beginning a Control Plane Only update, you must:

* You have paused worker nodes' machine config pools. This prevents worker nodes from being rebooted twice.

* You have disabled automatic workload updates. This prevents {VirtProductName} from migrating or evicting virtual machines (VMs) until you update to the target EUS version.

[NOTE]
====
By default, {VirtProductName} automatically updates workloads, such as the `virt-launcher` pod, when you update the {VirtProductName} Operator. You can configure this behavior in the `spec.workloadUpdateStrategy` stanza of the `HyperConverged` custom resource.
====
