// Module included in the following assembly:
//
// * virt/storage/virt-automatic-bootsource-updates.adoc
//

:_mod-docs-content-type: PROCEDURE
[id="virt-configuring-default-and-virt-default-storage-class_{context}"]
= Configuring the default and virt-default storage classes

A storage class determines how persistent storage is provisioned for workloads. In {VirtProductName}, the virt-default storage class takes precedence over the cluster default storage class and is used specifically for virtualization workloads. Only one storage class should be set as virt-default or cluster default at a time. If multiple storage classes are marked as default, the virt-default storage class overrides the cluster default. To ensure consistent behavior, configure only one storage class as the default for virtualization workloads.

.Procedure

. Patch the current virt-default or a cluster-default storage class to false:
.. Identify all storage classes currently marked as virt-default:
+
[source,terminal]
----
$ oc get sc -o json| jq '.items[].metadata|select(.annotations."storageclass.kubevirt.io/is-default-virt-class"=="true")|.name'
----
+
.. For each storage class returned, remove the virt-default annotation by running:
+
[source,terminal]
----
$ oc patch storageclass <storage_class_name> -p '{"metadata": {"annotations": {"storageclass.kubevirt.io/is-default-virt-class": "false"}}}'
----
+
.. Identify all storage classes currently marked as cluster-default:
+
[source,terminal]
----
$ oc get sc -o json| jq '.items[].metadata|select(.annotations."storageclass.kubernetes.io/is-default-class"=="true")|.name'
----
+
.. For each storage class returned, remove the cluster-default annotation by running:
+
[source,terminal]
----
$ oc patch storageclass <storage_class_name> -p '{"metadata": {"annotations": {"storageclass.kubernetes.io/is-default-class": "false"}}}'
----

. Set a new default storage class:
.. Assign the virt-default role to a storage class:
+
[source,terminal]
----
oc patch storageclass <storage_class_name> -p '{"metadata": {"annotations": {"storageclass.kubevirt.io/is-default-virt-class": "true"}}}'
----
+
.. Alternatively, assign the cluster-default role to a storage class
+
[source,terminal]
----
oc patch storageclass <storage_class_name> -p '{"metadata": {"annotations": {"storageclass.kubernetes.io/is-default-class": "true"}}}'
----