// Module included in the following assembly:
//
// * virt/storage/virt-automatic-bootsource-updates.adoc
//

:_mod-docs-content-type: PROCEDURE
[id="virt-configuring-storage-class-bootsource-update_{context}"]
= Configuring a storage class for custom boot source updates

You can override the default storage class by editing the `HyperConverged` custom resource (CR).

[IMPORTANT]
====
Boot sources are created using the default storage class. When the default storage class changes, old boot sources are automatically updated using the new default storage class.

If boot source images were stored as VolumeSnapshots and both the cluster default and `virt-default` storage class have been unset, the VolumeSnapshots will be cleaned up and new DataVolumes will be created. However they will not start importing until a default storage class is set.

To ensure stable behavior and avoid unnecessary re-importing, you can specify the `storageClassName` in the `dataImportCronTemplates` section of the `HyperConverged` resource.
====

.Procedure

. Open the `HyperConverged` CR in your default editor by running the following command:
+
[source,terminal,subs="attributes+"]
----
$ oc edit hyperconverged kubevirt-hyperconverged -n {CNVNamespace}
----

. Add the `dataImportCronTemplate` to the spec section of the `HyperConverged` resource and set the `storageClassName`:
+
[source,yaml]
----
apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  name: kubevirt-hyperconverged
spec:
  dataImportCronTemplates:
  - metadata:
      name: rhel9-image-cron
    spec:
      template:
        spec:
          storage:
            storageClassName: <storage_class> <1>
      schedule: "0 */12 * * *" <2>
      managedDataSource: <data_source> <3>
# ...
----
<1> Define the storage class.
<2> Required: Schedule for the job specified in cron format.
<3> Required: The data source to use.
+
--
[NOTE]
----
For the custom image to be detected as an available boot source, the value of the `spec.dataVolumeTemplates.spec.sourceRef.name` parameter in the VM template must match this value.
----
--

. Remove the `storageclass.kubernetes.io/is-default-class` annotation from the current default storage class.
.. Retrieve the name of the current default storage class by running the following command:
+
[source,terminal]
----
$ oc get storageclass
----
+
.Example output
[source,text]
----
NAME                          PROVISIONER                      RECLAIMPOLICY  VOLUMEBINDINGMODE    ALLOWVOLUMEEXPANSION  AGE
csi-manila-ceph               manila.csi.openstack.org         Delete         Immediate            false                 11d
hostpath-csi-basic (default)  kubevirt.io.hostpath-provisioner Delete         WaitForFirstConsumer false                 11d <1>
----
+
<1> In this example, the current default storage class is named `hostpath-csi-basic`.

.. Remove the annotation from the current default storage class by running the following command:
+
[source,terminal]
----
$ oc patch storageclass <current_default_storage_class> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}' <1>
----
<1> Replace `<current_default_storage_class>` with the `storageClassName` value of the default storage class.

. Set the new storage class as the default by running the following command:
+
[source,terminal]
----
$ oc patch storageclass <new_storage_class> -p '{"metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}' <1>
----
<1> Replace `<new_storage_class>` with the `storageClassName` value that you added to the `HyperConverged` CR.

. Wait for the HyperConverged Operator (HCO) and Storage Solution Provider (SSP) resources to complete reconciliation.

. Delete any outdated DataVolume and VolumeSnapshot objects from the `openshift-virtualization-os-images` namespace.
+
[source,terminal]
----
$ oc delete DataVolume,VolumeSnapshot -n openshift-virtualization-os-images --selector=cdi.kubevirt.io/dataImportCron
----

. Wait for all DataSources to reach a "Ready - True" status. DataSources can reference either a PersistentVolumeClaim (PVC) or a VolumeSnapshot. To check the expected source format, run the following command:
+
[source,terminal]
----
$ oc get storageprofile <storage_class_name> -o json | jq .status.dataImportCronSourceFormat
----